services:
  db:
   image: ontology_server
   environment:
     SPARQL_UPDATE: "true"
     DEFAULT_GRAPH: "http://www.ontology_server.com/default_graph"
   volumes:
     - ontology_server_volume:/data
   ports:
     - "8890:8890"

volumes:
 ontology_server_volume:
    external: true
